[connections.gsheets]
type = "gspread"
credentials = "..."  # (base64-encoded Google service account JSON)
spreadsheet = "https://docs.google.com/spreadsheets/d/1ghF0xwI74MvlIEQ-ny6_Uc8kGoyMC7rK_TLGMD6ml48"