[github]
username = "grinzsolo"
repo = "nnihd2"
token = "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"

[line_notify]
token = "etyqehY7qYEK4Wq6WiXFIW72cUk1ywWgf3ex4m3L8MwtebbJh2+lAfjKrnqUiH7BGFa/AfLJBq1MCyq4hvi4gJ7oPT2o5exTEaW268vV+xekYcsgsAieeeQYHXC4MgOYWMm4+TNEuXOBKRczHMPB1wdB04t89/1O/w1cDnyilFU="
